### ISSUE TITLE
Attachment ContentID is not getting added to the email. 

### ISSUE THREAD

**Issue by maverickames** [mailersend/mailersend-go#33]
Go code
`mailersend.Attachment{Filename: "filename.png", Content: encoded, ID: "filename"}`

Email Source
```
Content-Type: image/png; name=filename.png
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=filename.png
```

Seems its messing 'Content-ID: <idname>'

**Comment by robgordon89** [comment]
👋 hey @maverickames thanks for reporting this it looks like this is not yet implemented on the API yet and so the Content-ID is missing from the email.

I will track this issue internally and let you know when this is fixed, I don't currently have any timeframe on this at the moment.
