### ISSUE TITLE
Feature Request: Canonical types for webhook events

### ISSUE THREAD

**Issue by davidsbond** [mailersend/mailersend-go#80]
Hello! I've started using the Go SDK and noticed it lacks types for webhooks. Since there are an [extensive number of event types](https://developers.mailersend.com/api/v1/webhooks.html#webhooks-overview) it'd be great if this repo contained canonical types I could import rather than defining & maintaining them all myself. 

Many of the [types that look like they would be usable](https://github.com/mailersend/mailersend-go/blob/main/activity.go#L20) are unexported currently

Thanks!

**Comment by robgordon89** [comment]
@davidsbond would welcome a PR to add this 👍

**Comment by davidsbond** [comment]
Hey @robgordon89, thanks for looking at this!

Having just the event type names is a good start, but I was thinking more along the lines of having types for all the individual possible event payloads to simplify writing handlers in Go. Similar to how stripe exposes this in their Go SDK.

I also have code for verifying webhook signatures in Go that I could raise a PR for if you'd like.

**Comment by davidsbond** [comment]
To illustrate, to just handle the `activity.sent` webhook, I need to define all of this:

```go
package mailersend

import (
	"encoding/json"
	"time"
)

type (
	Event struct {
		Type      EventType       `json:"type"`
		DomainID  string          `json:"domainId"`
		CreatedAt time.Time       `json:"created_at"`
		WebhookID string          `json:"webhookId"`
		URL       string          `json:"url"`
		Data      json.RawMessage `json:"data"`
	}

	ActivitySent struct {
		Object     string    `json:"object"`
		ID         string    `json:"id"`
		Type       string    `json:"type"`
		CreatedAt  time.Time `json:"created_at"`
		Email      Email     `json:"email"`
		TemplateID string    `json:"template_id"`
	}

	Email struct {
		Object    string    `json:"object"`
		ID        string    `json:"id"`
		CreatedAt time.Time `json:"created_at"`
		From      string    `json:"from"`
		Subject   string    `json:"subject"`
		Status    string    `json:"status"`
		Tags      []string  `json:"tags"`
		Message   Message   `json:"message"`
		Recipient Recipient `json:"recipient"`
	}

	Message struct {
		Object    string    `json:"object"`
		ID        string    `json:"id"`
		CreatedAt time.Time `json:"created_at"`
	}

	Recipient struct {
		Object    string    `json:"object"`
		ID        string    `json:"id"`
		Email     string    `json:"email"`
		CreatedAt time.Time `json:"created_at"`
	}

	EventType string
)

const (
	EventTypeActivitySent EventType = "activity.sent"
)

```

**Comment by davidsbond** [comment]
@robgordon89, please see https://github.com/mailersend/mailersend-go/pull/86 for signature validation. I've also added a `WebhookEvent` type but happy to swap that with whatever types you expose.

I've put it in draft as I'm not 100% what you'd like with regards to testing.

**Comment by robgordon89** [comment]
@davidsbond thanks so much I'll take a look at this tomorrow morning 👍

**Comment by robgordon89** [comment]
just thinking about this more this SDK is more about using our API and not handling webhooks 🤔 

Wondering if it is better to keep this separate

**Comment by robgordon89** [comment]
im gonna vote to keep this up to the developer, for implementing the webhooks, this is more of a wrapper around the API 👍
